 --- Insertion information de tests

INSERT INTO AgilBDD.tests (Title, NbQuestions, Language, Scale, Duration, PointsQuestion) VALUES ('Quizz PO', '20', 'Français', '20', '15', '500');
INSERT INTO AgilBDD.tests (Title, NbQuestions, Language, Scale, Duration, PointsQuestion) VALUES ('Quizz PO', '40', 'Français', '40', '30', '250');
INSERT INTO AgilBDD.tests (Title, NbQuestions, Language, Scale, Duration, PointsQuestion) VALUES ('Quizz PO', '80', 'Français', '80', '60', '125');
INSERT INTO AgilBDD.tests (Title, NbQuestions, Language, Scale, Duration, PointsQuestion) VALUES ('Quizz PO', '20', 'Anglais', '20', '15', '500');
INSERT INTO AgilBDD.tests (Title, NbQuestions, Language, Scale, Duration, PointsQuestion) VALUES ('Quizz PO', '40', 'Anglais', '40', '30', '250');
INSERT INTO AgilBDD.tests (Title, NbQuestions, Language, Scale, Duration, PointsQuestion) VALUES ('Quizz PO', '80', 'Anglais', '80', '60', '125');
INSERT INTO AgilBDD.tests (Title, NbQuestions, Language, Scale, Duration, PointsQuestion) VALUES ('Quizz SCRUM', '20', 'Français', '20', '15', '500');
INSERT INTO AgilBDD.tests (Title, NbQuestions, Language, Scale, Duration, PointsQuestion) VALUES ('Quizz SCRUM', '40', 'Français', '40', '30', '250');
INSERT INTO AgilBDD.tests (Title, NbQuestions, Language, Scale, Duration, PointsQuestion) VALUES ('Quizz SCRUM', '80', 'Français', '80', '60', '125');
INSERT INTO AgilBDD.tests (Title, NbQuestions, Language, Scale, Duration, PointsQuestion) VALUES ('Quizz SCRUM', '20', 'Anglais', '20', '15', '500');
INSERT INTO AgilBDD.tests (Title, NbQuestions, Language, Scale, Duration, PointsQuestion) VALUES ('Quizz SCRUM', '40', 'Anglais', '40', '30', '250');
INSERT INTO AgilBDD.tests (Title, NbQuestions, Language, Scale, Duration, PointsQuestion) VALUES ('Quizz SCRUM', '80', 'Anglais', '80', '60', '125');

---- Insertion Questions des tests

INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('What variables should a Product Owner consider when ordering the Product Backlog?', 'The Product Owner is responsible for ordering the items in the Product Backlog to best achieve goals and missions, thereby optimizing the value of the work the Development Team performs. How this is done, and what value means, may vary widely across organizations', 0, 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('What preconditions must be fulfilled in order to allow Sprint Planning to begin?', 'Sprint Planning serves to plan the work to be performed in the Sprint. This plan is created by the collaborative work of the entire Scrum Team. Sprint Planning is timeboxed to a maximum of eight hours for a onemonth Sprint. What can be achieved in this timebox may be influenced by additional practices that are however not prescribed by Scrum', 0, 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('The process of regular inspection and adaptation employs knowledgeable and skilled inspectors. What are two ways in which the Product Owner takes the lead in the inspection process?', 'Scrum users must frequently inspect Scrum artifacts and progress to detect undesirable variances. The primary tool for the Product Owner to uphold transparency is the Product Backlog. Product Backlog is a living artifact that is actively maintained and updated to reflect reality. At the Sprint Review, attendees collaborate on the next things that could be done to optimize value, which is processed into an updated Product Backlog', 1, 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('The Product Owner’s authority to change and update the Product Backlog is unlimited, except for:', 'For the Product Owner to succeed, the entire organization must respect his or her decisions. No one is allowed to tell the Development Team to work from a different set of requirements, and the Development Team isn’t allowed to act on what anyone else says', 0,'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('What two things best help the Product Owner manage the value of a product?', 'The Product Owner manages Product Backlog against the assumption that value will be generated. Indications of value on Product Backlog are useful but are only a prediction until validated against users and market', 1 , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('In order to make investment decisions, the Product Owner is likely to look at the Total Cost of Ownership (TCO) of the product being built. What costs will a Product Owner take into account?', 'The owner of a product is not only accountable for development and release of a product, but also the cost of maintaining and operating the product. If a person ‘owns’ the product, he/she can be expected to be responsible for the complete lifecycle of a product', 0 , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('Must the Product Owner be present at the Sprint retrospective?', 'The Sprint retrospective is an opportunity for the Scrum Team to inspect itself and create a plan for improvements to be enacted during the next Sprint', 0, 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('Which two statements explain why the definition of ‘Done’ is important to the Product Owner?', 'All Scrum Team members must have a shared understanding of what it means for work to be complete, to ensure transparency. This is the definition of ‘Done’ for the Scrum Team and is used to assess when work is complete on the product Increment. The Increment reviewed at the Sprint Review must be useable, so a Product Owner may choose to immediately release it', 1, 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('Which description best fits the role of the Product Owner?', 'The Product Owner is responsible for maximizing the value of the product. How this is done will vary widely', 0, 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('What are two typical activities for a Product Owner in a Sprint?', 'Product Backlog refinement is an ongoing process in which the Product Owner and the Development Team collaborate on the details of Product Backlog items, The Product Owner represents the stakeholders to the Scrum Team. This typically requires active interaction in order to be able to represent stakeholders and their needs', 1, 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('A first Sprint can start before the Product Owner has a complete and exhaustive Product Backlog in place', 'A first Sprint requires no more than a Product Owner, a team, and enough ideas to potentially complete a full Sprint', 0, 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('Learning turns into "validated learning" when assumptions and goals can be assessed through results. What is a key way for a Product Owner to apply "validated learning"?', 'The Product Owner manages Product Backlog against the assumption that value will be generated. This assumption remains invalidated when not checked against users and market', 0, 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('The Development Team finds out during the Sprint that they aren’t likely to build everything they forecasted. What would you expect a Product Owner to do?', 'During the Sprint scope may be clarified and renegotiated between the Product Owner and Development Team as more is learned', 0, 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('Who creates the definition of ‘Done’?', 'If ‘done’ for an increment is not a convention of the development organization, the Development Team of the Scrum Team must define a definition of ‘done’ appropriate for the product. If the definition of ‘done’ is part of the conventions, standards or guidelines of the development organization, all Scrum Teams must follow it as a minimum. The Development Team of the Scrum Team can complement it with elements specific for the product or context ', 0, 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('To what extent does technical debt limit the value a Product Owner can get from a product? Select two answers', '', 1, 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('How important is it for a Product Owner to order Product Backlog items by value points?', 'Indications of value on Product Backlog are useful but are only a prediction until validated against users and market', 0, 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('What is the Product Owner accountable for in Scrum?', 'The Product Owner is responsible for maximizing the value of the product and the work of the Development Team. The primary tool to do so is the Product Backlog',0 , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('What two things should be done if the Product Owner is unavailable?', 'The Scrum framework consists of Scrum Teams and their associated roles, events, artifacts, and rules. Each component within the framework serves a specific purpose and is essential to Scrum’s success and usage. The Scrum Team consists of a Product Owner, the Development Team, and a Scrum Master. The Product Owner is responsible for maximizing the value of the product and the work of the Development Team. In the absence of a Product Owner, the latter accountability is not performed', 1, 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('What two phrases best describe the relationship of the Product Owner and the Development Team?', 'The Product owner clearly expresses Product Backlog items, ensuring the Development Team understands items in the Product Backlog to the level needed for developing them and creating the value the Product Owner envisions. Scope may be re-negotiated if the effort grows much higher than anticipated', 1 , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('When can the Product Backlog be updated?', 'The Product Backlog is dynamic; it constantly changes to identify what the product needs in order to be appropriate, competitive, and useful. Product Backlog items can be updated at any time by the Product Owner or at the Product Owner’s discretion', 0 , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('A Product Owner is entitled to postpone the start of a new Sprint after the conclusion of a previous Sprint for the following reason:', 'A new Sprint starts immediately after the conclusion of the previous Sprint', 0, 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('The Sprint Review is the only time at which stakeholder feedback is taken into account', 'A Product Owner engages actively and regularly with stakeholders. However, to limit the disturbance to the development progress and keep focus high, the stakeholders have a formal role in the process at the Sprint Review only', 0, 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('What best describes the relationship of the Product Owner and the stakeholders?', 'The Product Owner represents the stakeholders to the Scrum Team, which includes representing their desired requirements in the Product Backlog. The Product Owner has the final call over the Product Backlog', 0, 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('The Product Owner manages the Product Backlog. Who is accountable for estimating the effort to complete the Product Backlog items?', 'The Development Team is responsible for all estimates. The people who will perform the work make the final estimate', 0, 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('It is mandatory for the Product Owner to monitor and share progress of Product Backlog through:', 'Various projective practices upon trending have been used to forecast progress, like burn-downs, burn-ups, or cumulative flows. These have proven useful, but none are mandatory and care should be taken because none can replace the importance of empiricism. What will happen is unknown, no matter what has happened', 0, 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('A Product Owner is essentially the same thing as a traditional Project Manager?', 'A traditional project manager is responsible for all aspects of a project; costs, resources, execution, release, planning, capacity. Scrum is a framework for complex product development, regardless of whether the work is organized in projects. The Product Owner is responsible for maximizing the value of the product and the work performed, a responsibility that is complemented by the specific accountabilities of the Development Team and the Scrum Master', 0, 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('The value delivered by a product can only be determined by revenue', 'Value is likely to vary across products and organizations', 0, 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('How does an organization know that a product built through Scrum is successful?', 'Scrum Teams deliver products iteratively and incrementally, maximizing opportunities for feedback. If a product isn’t released, the opportunity to capture user and market feedback is lost', 0, 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('How can a Product Owner use time-boxed Sprints to obtain feedback from users and the market?', 'The Product Owner manages Product Backlog against the assumption that value will be generated. This assumption remains invalidated when not checked against users and market. When a Sprint’s horizon is too long, you increase the risk that what is being developed may no longer be desired. Sprints limit risk to one calendar month or less of work', 0, 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('The optimal length of a Sprint is?', 'La durée maximale d’un sprint est d’un mois (4 semaines), mais la durée optimale dépend de l’équipe et du contexte du projet, avec une préférence pour les sprints les plus courts pour réduire le risque métier', 0, 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('Sprints are never longer than a calendar month', 'Scrum offers a maximum duration of 4 weeks for a sprint', 0, 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('What does Scrum mean by Transparency?', 'A common language referring to the process must be shared by all participants; and, for example : Significant aspects of the process must be visible to those responsible for the outcome (including stakeholders). Transparency requires those aspects be defined by a common standard so observers share a common understanding of what is being seen. Those performing the work and those inspecting the resulting increment must share a common definition of « Done »', 0, 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');
INSERT INTO AgilBDD.tests (Question, Comment, , language) VALUES ('', '', , 'Anglais');

