 --- Insertion information de tests

INSERT INTO AgilBDD.tests (Title, NbQuestions, Language, Scale, Duration, PointsQuestion) VALUES ('Quizz PO', '20', 'Français', '20', '15', '500');
INSERT INTO AgilBDD.tests (Title, NbQuestions, Language, Scale, Duration, PointsQuestion) VALUES ('Quizz PO', '40', 'Français', '40', '30', '250');
INSERT INTO AgilBDD.tests (Title, NbQuestions, Language, Scale, Duration, PointsQuestion) VALUES ('Quizz PO', '80', 'Français', '80', '60', '125');
INSERT INTO AgilBDD.tests (Title, NbQuestions, Language, Scale, Duration, PointsQuestion) VALUES ('Quizz PO', '20', 'Anglais', '20', '15', '500');
INSERT INTO AgilBDD.tests (Title, NbQuestions, Language, Scale, Duration, PointsQuestion) VALUES ('Quizz PO', '40', 'Anglais', '40', '30', '250');
INSERT INTO AgilBDD.tests (Title, NbQuestions, Language, Scale, Duration, PointsQuestion) VALUES ('Quizz PO', '80', 'Anglais', '80', '60', '125');
INSERT INTO AgilBDD.tests (Title, NbQuestions, Language, Scale, Duration, PointsQuestion) VALUES ('Quizz SCRUM', '20', 'Français', '20', '15', '500');
INSERT INTO AgilBDD.tests (Title, NbQuestions, Language, Scale, Duration, PointsQuestion) VALUES ('Quizz SCRUM', '40', 'Français', '40', '30', '250');
INSERT INTO AgilBDD.tests (Title, NbQuestions, Language, Scale, Duration, PointsQuestion) VALUES ('Quizz SCRUM', '80', 'Français', '80', '60', '125');
INSERT INTO AgilBDD.tests (Title, NbQuestions, Language, Scale, Duration, PointsQuestion) VALUES ('Quizz SCRUM', '20', 'Anglais', '20', '15', '500');
INSERT INTO AgilBDD.tests (Title, NbQuestions, Language, Scale, Duration, PointsQuestion) VALUES ('Quizz SCRUM', '40', 'Anglais', '40', '30', '250');
INSERT INTO AgilBDD.tests (Title, NbQuestions, Language, Scale, Duration, PointsQuestion) VALUES ('Quizz SCRUM', '80', 'Anglais', '80', '60', '125');



---------------------------- Insertion des questions des quizz



---- INSERTION QUESTIONS OF PO QUIZZ IN ENGLISH

--- 1er jeu de données

INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES ('What variables should a Product Owner consider when ordering the Product Backlog?', 'The Product Owner is responsible for ordering the items in the Product Backlog to best achieve goals and missions, thereby optimizing the value of the work the Development Team performs. How this is done, and what value means, may vary widely across organizations', 0, 'PO','Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES ('What preconditions must be fulfilled in order to allow Sprint Planning to begin?', 'Sprint Planning serves to plan the work to be performed in the Sprint. This plan is created by the collaborative work of the entire Scrum Team. Sprint Planning is timeboxed to a maximum of eight hours for a onemonth Sprint. What can be achieved in this timebox may be influenced by additional practices that are however not prescribed by Scrum', 0, 'PO', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES ('The process of regular inspection and adaptation employs knowledgeable and skilled inspectors. What are two ways in which the Product Owner takes the lead in the inspection process?', 'Scrum users must frequently inspect Scrum artifacts and progress to detect undesirable variances. The primary tool for the Product Owner to uphold transparency is the Product Backlog. Product Backlog is a living artifact that is actively maintained and updated to reflect reality. At the Sprint Review, attendees collaborate on the next things that could be done to optimize value, which is processed into an updated Product Backlog', 1, 'PO', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES ('The Product Owner’s authority to change and update the Product Backlog is unlimited, except for:', 'For the Product Owner to succeed, the entire organization must respect his or her decisions. No one is allowed to tell the Development Team to work from a different set of requirements, and the Development Team isn’t allowed to act on what anyone else says', 0, 'PO', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES ('What two things best help the Product Owner manage the value of a product?', 'The Product Owner manages Product Backlog against the assumption that value will be generated. Indications of value on Product Backlog are useful but are only a prediction until validated against users and market', 1 , 'PO', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES ('In order to make investment decisions, the Product Owner is likely to look at the Total Cost of Ownership (TCO) of the product being built. What costs will a Product Owner take into account?', 'The owner of a product is not only accountable for development and release of a product, but also the cost of maintaining and operating the product. If a person ‘owns’ the product, he/she can be expected to be responsible for the complete lifecycle of a product', 0 , 'PO', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES ('Must the Product Owner be present at the Sprint retrospective?', 'The Sprint retrospective is an opportunity for the Scrum Team to inspect itself and create a plan for improvements to be enacted during the next Sprint', 0, 'PO', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES ('Which two statements explain why the definition of ‘Done’ is important to the Product Owner?', 'All Scrum Team members must have a shared understanding of what it means for work to be complete, to ensure transparency. This is the definition of ‘Done’ for the Scrum Team and is used to assess when work is complete on the product Increment. The Increment reviewed at the Sprint Review must be useable, so a Product Owner may choose to immediately release it', 1, 'PO', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES ('Which description best fits the role of the Product Owner?', 'The Product Owner is responsible for maximizing the value of the product. How this is done will vary widely', 0, 'PO', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES ('What are two typical activities for a Product Owner in a Sprint?', 'Product Backlog refinement is an ongoing process in which the Product Owner and the Development Team collaborate on the details of Product Backlog items, The Product Owner represents the stakeholders to the Scrum Team. This typically requires active interaction in order to be able to represent stakeholders and their needs', 1, 'PO', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES ('A first Sprint can start before the Product Owner has a complete and exhaustive Product Backlog in place', 'A first Sprint requires no more than a Product Owner, a team, and enough ideas to potentially complete a full Sprint', 0, 'PO', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES ('Learning turns into "validated learning" when assumptions and goals can be assessed through results. What is a key way for a Product Owner to apply "validated learning"?', 'The Product Owner manages Product Backlog against the assumption that value will be generated. This assumption remains invalidated when not checked against users and market', 0, 'PO', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES ('The Development Team finds out during the Sprint that they aren’t likely to build everything they forecasted. What would you expect a Product Owner to do?', 'During the Sprint scope may be clarified and renegotiated between the Product Owner and Development Team as more is learned', 0, 'PO', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES ('Who creates the definition of ‘Done’?', 'If ‘done’ for an increment is not a convention of the development organization, the Development Team of the Scrum Team must define a definition of ‘done’ appropriate for the product. If the definition of ‘done’ is part of the conventions, standards or guidelines of the development organization, all Scrum Teams must follow it as a minimum. The Development Team of the Scrum Team can complement it with elements specific for the product or context ', 0, 'PO', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES ('To what extent does technical debt limit the value a Product Owner can get from a product? Select two answers', '', 1, 'PO', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES ('How important is it for a Product Owner to order Product Backlog items by value points?', 'Indications of value on Product Backlog are useful but are only a prediction until validated against users and market', 0, 'PO', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES ('What is the Product Owner accountable for in Scrum?', 'The Product Owner is responsible for maximizing the value of the product and the work of the Development Team. The primary tool to do so is the Product Backlog',0 , 'PO', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES ('What two things should be done if the Product Owner is unavailable?', 'The Scrum framework consists of Scrum Teams and their associated roles, events, artifacts, and rules. Each component within the framework serves a specific purpose and is essential to Scrum’s success and usage. The Scrum Team consists of a Product Owner, the Development Team, and a Scrum Master. The Product Owner is responsible for maximizing the value of the product and the work of the Development Team. In the absence of a Product Owner, the latter accountability is not performed', 1, 'PO', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES ('What two phrases best describe the relationship of the Product Owner and the Development Team?', 'The Product owner clearly expresses Product Backlog items, ensuring the Development Team understands items in the Product Backlog to the level needed for developing them and creating the value the Product Owner envisions. Scope may be re-negotiated if the effort grows much higher than anticipated', 1 , 'PO','Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES ('When can the Product Backlog be updated?', 'The Product Backlog is dynamic; it constantly changes to identify what the product needs in order to be appropriate, competitive, and useful. Product Backlog items can be updated at any time by the Product Owner or at the Product Owner’s discretion', 0 , 'PO','Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES ('A Product Owner is entitled to postpone the start of a new Sprint after the conclusion of a previous Sprint for the following reason:', 'A new Sprint starts immediately after the conclusion of the previous Sprint', 0, 'PO', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES ('The Sprint Review is the only time at which stakeholder feedback is taken into account', 'A Product Owner engages actively and regularly with stakeholders. However, to limit the disturbance to the development progress and keep focus high, the stakeholders have a formal role in the process at the Sprint Review only', 0, 'PO', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES ('What best describes the relationship of the Product Owner and the stakeholders?', 'The Product Owner represents the stakeholders to the Scrum Team, which includes representing their desired requirements in the Product Backlog. The Product Owner has the final call over the Product Backlog', 0, 'PO','Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES ('The Product Owner manages the Product Backlog. Who is accountable for estimating the effort to complete the Product Backlog items?', 'The Development Team is responsible for all estimates. The people who will perform the work make the final estimate', 0, 'PO', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES ('It is mandatory for the Product Owner to monitor and share progress of Product Backlog through:', 'Various projective practices upon trending have been used to forecast progress, like burn-downs, burn-ups, or cumulative flows. These have proven useful, but none are mandatory and care should be taken because none can replace the importance of empiricism. What will happen is unknown, no matter what has happened', 0, 'PO', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES ('A Product Owner is essentially the same thing as a traditional Project Manager?', 'A traditional project manager is responsible for all aspects of a project; costs, resources, execution, release, planning, capacity. Scrum is a framework for complex product development, regardless of whether the work is organized in projects. The Product Owner is responsible for maximizing the value of the product and the work performed, a responsibility that is complemented by the specific accountabilities of the Development Team and the Scrum Master', 0, 'PO', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES ('The value delivered by a product can only be determined by revenue', 'Value is likely to vary across products and organizations', 0, 'PO', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES ('How does an organization know that a product built through Scrum is successful?', 'Scrum Teams deliver products iteratively and incrementally, maximizing opportunities for feedback. If a product isn’t released, the opportunity to capture user and market feedback is lost', 0, 'PO', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES ('How can a Product Owner use time-boxed Sprints to obtain feedback from users and the market?', 'The Product Owner manages Product Backlog against the assumption that value will be generated. This assumption remains invalidated when not checked against users and market. When a Sprint’s horizon is too long, you increase the risk that what is being developed may no longer be desired. Sprints limit risk to one calendar month or less of work', 0, 'PO', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES ('The optimal length of a Sprint is?', 'The maximum duration for a Sprint is 1 month (4 weeks), but the optimal duration depends on the team and on the project, with a preference for shortest duration because they minimize the risks or the business', 0, 'PO', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES ('Sprints are never longer than a calendar month', 'Scrum offers a maximum duration of 4 weeks for a sprint', 0, 'PO', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES ('What does Scrum mean by Transparency?', 'A common language referring to the process must be shared by all participants; and, for example : Significant aspects of the process must be visible to those responsible for the outcome (including stakeholders). Transparency requires those aspects be defined by a common standard so observers share a common understanding of what is being seen. Those performing the work and those inspecting the resulting increment must share a common definition of « Done »', 0, 'PO', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES ('What is the best definition of ‘Done’?', 'The "Definition of Done" is set by the SCRUM team,  and align the team on the work to be performed for an Increment to ve ready to deploy.',0 , 'PO', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES ('A servant leadership role includes:', 'One of the ways that the Scrum Master, as a servant leader, protects the team is by shielding it from interruptions',0 , 'PO', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES ('What are two ways in which the Product Owner manages Inspection of the Increment?', "Backlog Refinement brings the need to a greater level of maturity. The Sprint retrospective is meant to inspect the process and pratices and adapt them. Sprint Review lets the Product Owner inspect the lastest increment through a demo of the product and the collection of the user's feedbacks.", 1 , 'PO', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES ('Which should NOT take place at the daily Scrum?', 'The goal of a Daily Scrum is not to perform a status report, but to synchronize and share obstacles to progress. Product Owner is not mandatory at the Daily Scrum.', 0 , 'PO', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES ('Incremental delivery means:', '', 0, 'PO', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES ('The Product Owner does not have to be a single person but may be a committee or a shared responsibility between multiple individuals', "The Product Owner is a signle person, and his/her responsability can't be shared. In case of  multiple Product Owners, one single PO will effectively have this role.", 0, 'PO', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES ('Who updates work remaining during the Sprint?', '', 0 , 'PO', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES ('When does Adaptation occur in Scrum?', '', 0 , 'PO', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES ('The Product Owner creates the Sprint Goal in advance of the Sprint Planning meeting', '', 0, 'PO', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES ('An iteration takes place in a time frame with specific start and end dates, called a time-box. Which of the following is NOT an advantage of time-boxing?', '', 0, 'PO', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES ('Why does Scrum use different terminology?', '', 0, 'PO', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES ('The person responsible for the Scrum process, making sure it is used correctly and maximizing its benefit:', '', 0, 'PO', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES ('What happens if the customer no longer wants the feature that the Sprint Goal intended to meet?', '', 0 , 'PO', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES ('Who is NOT part of the Scrum Team?', '', 0 , 'PO', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES ('Scrum is NOT:', '', 0 , 'PO', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES ('The Product Owner is responsible for the definition of Done', 'The Development team is responsible for the definition of done. The Prooduct Owner can still reject an increment and ask the Definition of done to be improved', 0, 'PO', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES ('How much work must a Development Team do to a Product Backlog item it selects for the Sprint Backlog?', 'As much as it has told the Product Owner will be done for every Product Backlog item it selects in conformance with the defitinion of ‘Done’', 0 , 'PO', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES ('Which of the following reflects Scrum’s expectation of ‘validated learning’?', '', 0, 'PO', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES ('What is the purpose of the Sprint Review? (Choose three)', '', 1 , 'PO', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES ('What outcome is expected as Scrum Teams mature?', '',0 , 'PO', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES ('The Project Manager plays the following role in Scrum:', 'There is no project manager role in Scrum', 0 , 'PO', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES ('In Scrum, who is responsible for managing the team?', '', 0, 'PO', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES ('Who must do all of the work to ensure the Product Backlog items conform to the definition of “Done”?', '',0 , 'PO', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES ('The feedback from the Sprint Review impacts the next Sprint planning meeting', '', 0, 'PO', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES ('Why does a Development Team need a Sprint Goal?', 'A Sprint Goal gives a clear direction for the coming Sprint, and keeps the team aligned and focus', 0, 'PO', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES ('Scrum mandates the use of burndown charts', "Scrum doesn't mandate the use of burndown charts. All ways to track the remaining work can be used.", 0, 'PO', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES ('Suppose the current release will be complete after 6 two-week iterations. A team member is insisting that the Product Owner write the acceptance test cases for the entire release. How should the Scrum Master respond?', '', 0, 'PO', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES ('If the Sprint Backlog cannot be completed in a Sprint, who resolves the issue?', '', 0, 'PO', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES ('When does a Sprint get canceled or end early?', '', 0, 'PO', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES ('On an Agile team, the project leader works to remove impediments from blocking the team’s progress. This is known as what type of leadership?', '', 0, 'PO', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES ('Who creates the Sprint Goal?', '',0 , 'PO', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES ('What are the mandatory prerequisites to the Sprint Planning meeting?', '', 0 , 'PO', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES ('How do you ensure that performance requirements are addressed by the development team? (choose 2)', '', 1, 'PO', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES ('What is the most effective way to order the Product Backlog?', '', 0 , 'PO', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES ('Who is responsible for maximizing the value of the product backlog?', '', 0 , 'PO', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES ('Who is responsible for maximizing the value of the product?', '', 0, 'PO', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES ('Which two statements are true about the Sprint Backlog?', '', 1 , 'PO', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES ('The Product Backlog should be transparent to the entire organization', '', 0, 'PO', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES ('The optimum size of the Scrum Team is:', '', 0, 'PO', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES ('Which of the following three statements are true about the Product Owner role?', '', 1, 'PO', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES ('Pick three topics that can be addressed in the Sprint retrospective?', '', 1, 'PO', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES ('Which is a report of all the work that is ‘Done?’', '', 0 , 'PO', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES ('A new Sprint starts immediately following the previous Sprint', '',0 , 'PO', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES ('A product owner and project manager are basically the same thing in Scrum', '', 0 , 'PO', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES ('What is the primary tool of the Product Owner for measuring product progress?', 'The Product Backlog is the primary tool of the Product Owner for measuring product progress. The other tools are optional', 0 , 'PO', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES ('The sprint retrospective:', '', 0, 'PO', 'Anglais');

--- 2eme jeu de données 

INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES ('A baseline Product Backlog is called:', '', 0, 'PO', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES ('An important customer wants a new feature as soon as possible, what should the Product Owner do?', '', 0, 'PO', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES ('Scrum is both an iterative and incremental Agile process', '', 0, 'PO', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES ('Which statement is least accurate when providing a definition of ‘Done’?', '', 0, 'PO', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES ('There are 5 teams working on a product, how many Product Owners would there be?', '', 0, 'PO', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES ('If the Product Backlog is not ready for Sprint Planning, what happens?', 'If a Product Backlog isn’t ready for Sprint Planning, it means that the Development team will be unable to make a forecast (i.e. they won’t be able to create a Sprint Backlog), nor will they able to commit to making an incremental delivery of value. The sprint should be canceled. If the Product Backlog is not in a fit state for Sprint Planning, then the Sprint cannot start. Since a Sprint is a container for the other Scrum events, this means that those events cannot be held at all.What the team need to do is to refine the Product Backlog so that it is fit for purpose and a Sprint can start', 0, 'PO', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES ('On Agile teams, conflict is to be avoided at all cost', 'Innovation occurs only with the free interchange of conflicting ideas', 0, 'PO', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES ('Backlog Grooming and Backlog Refinement are the same thing', '', 0, 'PO', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES ('Everyone must stand up at the Daily Scrum', 'Though it is a best practice, the Scrum Guide does not mandate standing at the Daily Scrum', 0, 'PO', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES ('Sprint burndown charts are an efficient tracking tool because they show:', '', 0, 'PO', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES ('What should management consider when determining how to scale Scrum?', '', 0, 'PO', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES ('What is the benefit of ordering the Product Backlog using value points?', '', 0, 'PO', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES ('The Scrum Master’s job is to work with the Scrum Team and the organization to increase the awareness of the artifacts. Which pillar of Scrum does this represent?', '', 0, 'PO', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES ('Which TWO things do NOT occur in the first Sprint?', '', 1, 'PO', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES ('Why would the Product Owner concern themselves with technical debt?', '', 0, 'PO', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES ('', '', 0, 'PO', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES ('', '', 0, 'PO', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES ('', '', 0, 'PO', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES ('', '', 0, 'PO', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES ('', '', 0, 'PO', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES ('', '', 0, 'PO', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES ('', '', 0, 'PO', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES ('', '', 0, 'PO', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES ('', '', 0, 'PO', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES ('', '', 0, 'PO', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES ('', '', 0, 'PO', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES ('', '', 0, 'PO', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES ('', '', 0, 'PO', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES ('', '', 0, 'PO', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES ('', '', 0, 'PO', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES ('', '', 0, 'PO', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES ('', '', 0, 'PO', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES ('', '', 0, 'PO', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES ('', '', 0, 'PO', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES ('', '', 0, 'PO', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES ('', '', 0, 'PO', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES ('', '', 0, 'PO', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES ('', '', 0, 'PO', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES ('', '', 0, 'PO', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES ('', '', 0, 'PO', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES ('', '', 0, 'PO', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES ('', '', 0, 'PO', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES ('', '', 0, 'PO', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES ('', '', 0, 'PO', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES ('', '', 0, 'PO', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES ('', '', 0, 'PO', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES ('', '', 0, 'PO', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES ('', '', 0, 'PO', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES ('', '', 0, 'PO', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES ('', '', 0, 'PO', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES ('', '', 0, 'PO', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES ('', '', 0, 'PO', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES ('', '', 0, 'PO', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES ('', '', 0, 'PO', 'Anglais');



 
 ----- INSERTION QUESTIONS FOR SCRUM QUIZZ IN ENGLISH


INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES('', '', , 'SCRUM', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES('', '', , 'SCRUM', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES('', '', , 'SCRUM', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES('', '', , 'SCRUM', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES('', '', , 'SCRUM', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES('', '', , 'SCRUM', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES('', '', , 'SCRUM', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES('', '', , 'SCRUM', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES('', '', , 'SCRUM', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES('', '', , 'SCRUM', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES('', '', , 'SCRUM', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES('', '', , 'SCRUM', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES('', '', , 'SCRUM', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES('', '', , 'SCRUM', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES('', '', , 'SCRUM', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES('', '', , 'SCRUM', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES('', '', , 'SCRUM', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES('', '', , 'SCRUM', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES('', '', , 'SCRUM', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES('', '', , 'SCRUM', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES('', '', , 'SCRUM', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES('', '', , 'SCRUM', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES('', '', , 'SCRUM', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES('', '', , 'SCRUM', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES('', '', , 'SCRUM', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES('', '', , 'SCRUM', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES('', '', , 'SCRUM', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES('', '', , 'SCRUM', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES('', '', , 'SCRUM', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES('', '', , 'SCRUM', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES('', '', , 'SCRUM', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES('', '', , 'SCRUM', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES('', '', , 'SCRUM', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES('', '', , 'SCRUM', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES('', '', , 'SCRUM', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES('', '', , 'SCRUM', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES('', '', , 'SCRUM', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES('', '', , 'SCRUM', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES('', '', , 'SCRUM', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES('', '', , 'SCRUM', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES('', '', , 'SCRUM', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES('', '', , 'SCRUM', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES('', '', , 'SCRUM', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES('', '', , 'SCRUM', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES('', '', , 'SCRUM', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES('', '', , 'SCRUM', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES('', '', , 'SCRUM', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES('', '', , 'SCRUM', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES('', '', , 'SCRUM', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES('', '', , 'SCRUM', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES('', '', , 'SCRUM', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES('', '', , 'SCRUM', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES('', '', , 'SCRUM', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES('', '', , 'SCRUM', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES('', '', , 'SCRUM', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES('', '', , 'SCRUM', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES('', '', , 'SCRUM', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES('', '', , 'SCRUM', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES('', '', , 'SCRUM', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES('', '', , 'SCRUM', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES('', '', , 'SCRUM', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES('', '', , 'SCRUM', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES('', '', , 'SCRUM', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES('', '', , 'SCRUM', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES('', '', , 'SCRUM', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES('', '', , 'SCRUM', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES('', '', , 'SCRUM', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES('', '', , 'SCRUM', 'Anglais');
INSERT INTO AgilBDD.Questions (Question, Comment, Multiple, Categorie, Langue) VALUES('', '', , 'SCRUM', 'Anglais');



-------- INSERTION DES CHOIX QUESTIONS PO ANGLAIS


INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('Development cohesion as indicated by the Development Team', 1, 0);
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('Effort first, then value', 1, 0);
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('Lowest development cost in order to maximize ROI', 1, 0);
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('The availability of resources and skills for implementation', 1, 0);
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('Whatever is most appropriate for the Product Owner to achieve the product’s goals and to optimize the value received', 1, 1);
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('A clear and nonnegotiable Sprint Goal', 2, 0);
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('A clear but negotiable business objective for the Sprint', 2, 0);
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('A fully refined Product Backlog', 2, 0);
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('Enough "Ready" Product Backlog to fill the Sprint', 2, 0);
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('Formal budget approval to conduct another Sprint', 2, 0);
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('There are no such preconditions', 2, 1);
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('At the Daily Scrum the Product Owner inspects the Sprint burndown for progress towards a complete Increment and replanning the team’s work', 3 , 0);
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('At the end of Sprint Planning the Product Owner verifies the Sprint Backlog for completeness in order to allow the Sprint to start', 3, 0 );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('At the Sprint Review the Product Owner shares the current state of Product Backlog, which, combined with the inspection of the Increment, leads to an updated Product Backlog', 3, 1);
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('The Product Owner invites stakeholders to the Sprint Review to learn how the current state of the marketplace influences what is the most valuable thing to do next', 3, 1);
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('Decisions by the CFO, the CEO or the board of directors', 4, 0 );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('Decisions by the chief program manager', 4, 0 );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('High impact changes that have not been approved by the change request board', 4, 0 );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('Nothing. The entire organization must respect a Product Owner’s decisions', 4, 1);
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('Technical and architectural work that needs to be done first, as indicated by the chief enterprise architect', 4, 0 );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('Work for which impediments exist that the Scrum Master still needs to resolve', 4, 0 );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('Devising a formula for a neutral calculation of value', 5, 0);
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('Setting value on individual Product Backlog items using Value Poker', 5, 0);
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('The order of the Product Backlog', 5, 1);
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('Validating assumptions of value through frequent releases', 5, 1);
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('All investments required to conceive, develop, operate and maintain the product', 6, 1);
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('The accumulated cost over the earned value of the product', 6, 0);
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('The money spent on development of the product, often a fixed cost per Sprint multiplied by the Sprints required', 6, 0);
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('It is mandatory. The Sprint retrospective is an opportunity for the Scrum Team to assess its performance and improve itself', 7, 1);
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('It is not allowed. The Sprint retrospective is an opportunity for the Development Team to inspect itself', 7, 0);
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('It is optional. Attendance is only required when the Product Owner gets invited by the Scrum Master', 7, 0);
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('It assures the Increment reviewed at the Sprint review is usable so the Product Owner may choose to release it', 8, 1);
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('It creates transparency regarding progress within the Scrum Team', 8, 1);
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('It helps the Product Owner track the open work during a Sprint', 8, 0);
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('It identifies undone work that can be addressed in a separate Sprint', 8, 0);
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('Chief Analyst', 9, 0);
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('Project Manager 2.0', 9, 0);
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('Requirements Collector', 9, 0);
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('Scope Protector', 9, 0);
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('Value Maximizer', 9, 0);
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('Attend every Daily Scrum to answer functional questions on the discussed Sprint Backlog items', 10 , 0 );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('Collaborate with stakeholders, user communities and product managers', 10 , 1);
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('Create financial reporting upon the spent hours reported by the Development Team', 10 , 0);
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('Update the work plan for the Development Team on a daily basis', 10 , 0);
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('Work with the Development Team on Product Backlog refinement', 10 , 1);
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES("That's true", 11 , 1 );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES("That's false", 11 , 0 );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('Accept an Increment at the Sprint review to learn about the forecast of functionality that was developed', 12, 0 );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('Release an Increment to the market to learn about the business assumptions built into the product', 12, 1);
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('Set the Sprint Goal before selecting Product Backlog items at Sprint Planning to learn about a Development Team’s productivity', 12, 0);
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('Cancel the Sprint', 13, 0 );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('Change the Sprint Goal', 13, 0 );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('Inform management that more resources are needed', 13, 0 );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('Rework the selected Product Backlog items with the Development Team to meet the Sprint Goal', 13, 1 );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('Skip Product Backlog refinement activities', 13, 0 );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('The development organization (or Development Team if none is available from the development organization)', 14 , 1 );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('The Product Owner as he/she is responsible for the product’s success', 14 , 0 );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('The Scrum Master as he/she is responsible for the Development Team’s productivity', 14 , 0 );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('The Scrum Team, in a collaborative effort where the result is the common denominator of all members’ definitions', 14 , 0 );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('Technical debt causes a greater percentage of the product’s budget to be spent on maintenance of the product', 15 , 1);
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('Technical debt does not influence the delivery of value', 15 , 0);
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('Technical debt is not a Product Owner concern, because technical debt is only an issue for the Development Team', 15 , 0);
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('The velocity at which new functionality can be created is reduced when you have technical debt', 15 , 1);


--- 2eme jeu de données 



INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('', , );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('', , );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('', , );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('', , );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('', , );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('', , );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('', , );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('', , );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('', , );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('', , );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('', , );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('', , );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('', , );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('', , );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('', , );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('', , );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('', , );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('', , );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('', , );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('', , );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('', , );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('', , );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('', , );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('', , );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('', , );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('', , );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('', , );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('', , );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('', , );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('', , );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('', , );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('', , );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('', , );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('', , );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('', , );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('', , );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('', , );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('', , );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('', , );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('', , );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('', , );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('', , );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('', , );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('', , );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('', , );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('', , );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('', , );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('', , );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('', , );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('', , );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('', , );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('', , );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('', , );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('', , );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('', , );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('', , );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('', , );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('', , );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('', , );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('', , );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('', , );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('', , );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('', , );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('', , );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('', , );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('', , );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('', , );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('', , );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('', , );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('', , );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('', , );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('', , );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('', , );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('', , );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('', , );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('', , );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('', , );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('', , );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('', , );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('', , );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('', , );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('', , );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('', , );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('', , );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('', , );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('', , );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('', , );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('', , );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('', , );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('', , );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('', , );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('', , );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('', , );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('', , );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('', , );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('', , );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('', , );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('', , );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('', , );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('', , );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('', , );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('', , );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('', , );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('', , );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('', , );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('', , );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('', , );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('', , );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('', , );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('', , );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('', , );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('', , );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('', , );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('', , );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('', , );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('', , );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('', , );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('', , );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('', , );
INSERT INTO AgilBDD.Choice (answer, idQuestion, value) VALUES('', , );
