-- MySQL Script generated by MySQL Workbench
-- Tue Oct 22 18:35:54 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema AgilBDD
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema AgilBDD
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `AgilBDD` DEFAULT CHARACTER SET utf8 ;
USE `AgilBDD` ;

-- -----------------------------------------------------
-- Table `AgilBDD`.`Candidat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AgilBDD`.`Candidat` (
  `idCandidat` INT NOT NULL AUTO_INCREMENT,
  `Lastname` VARCHAR(85) NOT NULL,
  `Firstname` VARCHAR(85) NOT NULL,
  `Mail` VARCHAR(245) NOT NULL,
  `Position` VARCHAR(245) NULL,
  `Company` VARCHAR(245) NULL,
  PRIMARY KEY (`idCandidat`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AgilBDD`.`Tests`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AgilBDD`.`Tests` (
  `idTests` INT NOT NULL AUTO_INCREMENT,
  `Title` VARCHAR(245) NOT NULL,
  `NbQuestions` INT NOT NULL,
  `Language` VARCHAR(245) NOT NULL,
  `Scale` INT NOT NULL,
  `Duration` INT NOT NULL,
  PRIMARY KEY (`idTests`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AgilBDD`.`Resultats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AgilBDD`.`Resultats` (
  `idResultats` INT NOT NULL AUTO_INCREMENT,
  `idTests` INT NOT NULL,
  `Score` INT NOT NULL,
  `idCandidat` INT NOT NULL,
  PRIMARY KEY (`idResultats`),
  INDEX `idCandidat_idx` (`idCandidat` ASC) VISIBLE,
  INDEX `idTests_idx` (`idTests` ASC) VISIBLE,
  CONSTRAINT `idCandidat`
    FOREIGN KEY (`idCandidat`)
    REFERENCES `AgilBDD`.`Candidat` (`idCandidat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idTests`
    FOREIGN KEY (`idTests`)
    REFERENCES `AgilBDD`.`Tests` (`idTests`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AgilBDD`.`Choice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AgilBDD`.`Choice` (
  `idChoice` INT NOT NULL AUTO_INCREMENT,
  `answer` VARCHAR(845) NOT NULL,
  `idQuestions` INT NOT NULL,
  `value` TINYINT NOT NULL,
  PRIMARY KEY (`idChoice`),
  INDEX `idQuestions_idx` (`idQuestions` ASC) VISIBLE,
  CONSTRAINT `idQuestions`
    FOREIGN KEY (`idQuestions`)
    REFERENCES `AgilBDD`.`Questions` (`idQuestions`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AgilBDD`.`Questions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AgilBDD`.`Questions` (
  `idQuestions` INT NOT NULL AUTO_INCREMENT,
  `Question` VARCHAR(845) NOT NULL,
  `Comment` VARCHAR(845) NOT NULL,
  `Multiple responses` TINYINT NOT NULL,
  `Points` INT NOT NULL,
  `idTests` INT NOT NULL,
  PRIMARY KEY (`idQuestions`),
  INDEX `idTests_idx` (`idTests` ASC) VISIBLE,
  CONSTRAINT `idTests`
    FOREIGN KEY (`idTests`)
    REFERENCES `AgilBDD`.`Tests` (`idTests`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `responses`
    FOREIGN KEY ()
    REFERENCES `AgilBDD`.`Choice` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
