-- MySQL Script generated by MySQL Workbench
-- Wed Jan  8 15:13:23 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema QCMpsmpo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema QCMpsmpo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `QCMpsmpo` DEFAULT CHARACTER SET utf8 ;
USE `QCMpsmpo` ;

-- -----------------------------------------------------
-- Table `QCMpsmpo`.`Candidat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `QCMpsmpo`.`Candidat` (
  `idCandidat` INT NOT NULL AUTO_INCREMENT,
  `Lastname` VARCHAR(85) NOT NULL,
  `Firstname` VARCHAR(85) NOT NULL,
  `Mail` VARCHAR(245) NOT NULL,
  `Password` VARCHAR(245) NOT NULL,
  `Company` VARCHAR(245) NULL,
  `Position` VARCHAR(245) NULL,
  `Picture` VARCHAR(445) NULL,
  PRIMARY KEY (`idCandidat`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `QCMpsmpo`.`Tests`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `QCMpsmpo`.`Tests` (
  `idTests` INT NOT NULL AUTO_INCREMENT,
  `Title` VARCHAR(245) NOT NULL,
  `NbQuestions` INT NOT NULL,
  `Language` VARCHAR(245) NOT NULL,
  `Scale` INT NOT NULL,
  `Duration` INT NOT NULL,
  `PointsQuestion` INT NOT NULL,
  PRIMARY KEY (`idTests`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `QCMpsmpo`.`Resultats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `QCMpsmpo`.`Resultats` (
  `idResultats` INT NOT NULL AUTO_INCREMENT,
  `idTests` INT NOT NULL,
  `Score` INT NOT NULL,
  `idCandidat` INT NOT NULL,
  PRIMARY KEY (`idResultats`))
ENGINE = InnoDB;



ALTER TABLE `Resultats` ADD CONSTRAINT `FK_idTests` FOREIGN KEY (`idTests`) REFERENCES `Tests` (`idTests`);
ALTER TABLE `Resultats` ADD CONSTRAINT `FK_idCandidat` FOREIGN KEY (`idCandidat`) REFERENCES `Candidat` (`idCandidat`);

-- -----------------------------------------------------
-- Table `QCMpsmpo`.`Choice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `QCMpsmpo`.`Choice` (
  `idChoice` INT NOT NULL AUTO_INCREMENT,
  `answer` VARCHAR(845) NOT NULL,
  `idQuestions` INT NOT NULL,
  `value` TINYINT NOT NULL,
  PRIMARY KEY (`idChoice`))
ENGINE = InnoDB;



ALTER TABLE `Choice` ADD CONSTRAINT `FK_idQuestions` FOREIGN KEY (`idQuestions`) REFERENCES `Questions` (`idQuestions`);


-- -----------------------------------------------------
-- Table `QCMpsmpo`.`Questions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `QCMpsmpo`.`Questions` (
  `idQuestions` INT NOT NULL AUTO_INCREMENT,
  `Question` VARCHAR(845) NOT NULL,
  `Comment` VARCHAR(845) NOT NULL,
  `Multiple` TINYINT NOT NULL,
  `Categorie` VARCHAR(45) NOT NULL,
  `Langue` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idQuestions`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `QCMpsmpo`.`Admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `QCMpsmpo`.`Admin` (
  `idAdmin` INT NOT NULL AUTO_INCREMENT,
  `Lastname` VARCHAR(85) NOT NULL,
  `Firstname` VARCHAR(85) NOT NULL,
  `Mail` VARCHAR(245) NOT NULL,
  `Password` VARCHAR(245) NOT NULL,
  `Picture` VARCHAR(445) NULL,
  PRIMARY KEY (`idAdmin`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
